# File: scripts/convert_certs.py

from SCons.Script import DefaultEnvironment
import os

env = DefaultEnvironment()

# Menggunakan variabel yang disediakan PlatformIO untuk path yang andal
PROJECT_DIR = env.subst("$PROJECT_DIR")
KEY_FILE = os.path.join(PROJECT_DIR, "private.key")
CERT_FILE = os.path.join(PROJECT_DIR, "cert.pem")
INCLUDE_DIR = os.path.join(PROJECT_DIR, "include")
HEADER_FILE = os.path.join(INCLUDE_DIR, "certs.h")


def file_to_c_array(input_file, var_name):
    """Reads a file and converts its content to a C PROGMEM array."""
    try:
        with open(input_file, "rb") as f:
            data = f.read()
    except FileNotFoundError:
        # Saat dijalankan oleh PIO, lebih baik hentikan build jika file penting hilang
        print(f"FATAL ERROR: Certificate file '{input_file}' not found.")
        print("Please run 'openssl req ...' command to generate it.")
        env.Exit(1)  # Hentikan build dengan error

    data += b"\0"
    hex_array = ", ".join([f"0x{byte:02x}" for byte in data])
    c_code = f"const uint8_t {var_name}[] PROGMEM = {{\n  {hex_array}\n}};"
    c_code_len = f"const size_t {var_name}_len = sizeof({var_name});"

    return c_code, c_code_len


def generate_header_if_needed():
    # Cek apakah header perlu di-generate ulang
    # (jika header tidak ada, atau jika cert/key lebih baru dari header)

    generate = not os.path.exists(HEADER_FILE)
    if not generate:
        header_mtime = os.path.getmtime(HEADER_FILE)
        if os.path.exists(CERT_FILE) and os.path.getmtime(CERT_FILE) > header_mtime:
            generate = True
        if os.path.exists(KEY_FILE) and os.path.getmtime(KEY_FILE) > header_mtime:
            generate = True

    if not generate:
        print("Certs header (certs.h) is up to date.")
        return

    print("Generating new certs.h from certificate files...")

    key_code, key_len_code = file_to_c_array(KEY_FILE, "server_key")
    cert_code, cert_len_code = file_to_c_array(CERT_FILE, "server_cert")

    try:
        os.makedirs(INCLUDE_DIR, exist_ok=True)
        with open(HEADER_FILE, "w") as f:
            f.write("#ifndef CERTS_H\n")
            f.write("#define CERTS_H\n\n")
            f.write("#include <Arduino.h>\n\n")
            f.write(
                "// Self-signed certificate - Automatically generated by convert_certs.py\n"
            )
            f.write(cert_code + "\n")
            f.write(cert_len_code + "\n\n")
            f.write("// Private key - Automatically generated by convert_certs.py\n")
            f.write(key_code + "\n")
            f.write(key_len_code + "\n\n")
            f.write("#endif // CERTS_H\n")

        print(f"Header file successfully generated at: {HEADER_FILE}")
    except Exception as e:
        print(f"FATAL ERROR: Failed to write {HEADER_FILE}: {e}")
        env.Exit(1)


# Panggil fungsi utama
generate_header_if_needed()
