import os
import configparser
from SCons.Script import Import

Import("env") # noqa: F821

# 1. READ CONFIG FROM EXTERNAL FILE.
config = configparser.ConfigParser()
config.read("node_id.ini")

try:
    gh_id = config.get("settings", "gh_id")
    node_id = config.get("settings", "node_id")
    ota_ip_map = REDACTED
    for i in range(1, 11):
        key = f"ota_ip_{i}"
        ota_ip_map[i] = REDACTED
    gateway_ip_1 = config.get("settings", "gateway_ip_1", fallback="").strip()
    gateway_ip_2 = config.get("settings", "gateway_ip_2", fallback="").strip()
    firmware_version = config.get("settings", "firmware_version", fallback="0.0.0")
    factory_wifi_pass = REDACTED
    factory_api_token = REDACTED
    factory_ota_token = REDACTED
    default_data_url = config.get("settings", "data_upload_url", fallback="https://example.com/api/sensor")
    default_ota_url_base = REDACTED
except (configparser.Error, KeyError, OSError):
    print("!!! ERROR: File node_id.ini tidak ditemukan atau format salah !!!")
    gh_id = "0"
    node_id = "0"
    ota_ip_map = REDACTED
    gateway_ip_1 = ""
    gateway_ip_2 = ""
    firmware_version = "0.0.0"
    factory_wifi_pass = REDACTED
    factory_api_token = REDACTED
    factory_ota_token = REDACTED
    default_data_url = "https://example.com/api/sensor"
    default_ota_url_base = REDACTED


def _c_escape(value: str) -> str:
    if value is None:
        return ""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _to_int(value: str, fallback: int = 0) -> int:
    try:
        return int(value.strip())
    except (ValueError, AttributeError):
        return fallback


node_id_i = _to_int(node_id, 0)
selected_ota_ip = REDACTED

# Compile-time OTA IP selection from node map (1..10), else mDNS fallback.
if 1 <= node_id_i <= 10:
    selected_ota_ip = REDACTED

hostname = f"gh-{gh_id}-node-{node_id}.local"

# 3. GENERATE C++ HEADER FILE (Execute to inform firmware of ID).
header_content = f"""#ifndef DYNAMIC_NODE_CONFIG_H
#define DYNAMIC_NODE_CONFIG_H
// Automatically generated by inject_config.py.
// Edit 'node_id.ini' to change values.
#define GH_ID {gh_id}
#define NODE_ID {node_id}
#define FIRMWARE_VERSION "{firmware_version}"
#define FACTORY_WIFI_PASS "REDACTED"
#define FACTORY_API_TOKEN "REDACTED"
#define FACTORY_OTA_TOKEN "REDACTED"
#define DEFAULT_DATA_URL "{_c_escape(default_data_url)}"
#define DEFAULT_OTA_URL_BASE "REDACTED"
#define DEFAULT_GATEWAY_IP_GH1 "{_c_escape(gateway_ip_1)}"
#define DEFAULT_GATEWAY_IP_GH2 "{_c_escape(gateway_ip_2)}"
#endif
"""

output_file = os.path.join("include", "node_config.h")
needs_update = True

if os.path.exists(output_file):
    with open(output_file, "r", encoding="utf-8") as f:
        if f.read().strip() == header_content.strip():
            needs_update = False

if needs_update:
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(header_content)
    print(f"   -> Config header updated: GH={gh_id}, Node={node_id}")
else:
    print(f"   -> Config header unchanged: GH={gh_id}, Node={node_id}")

# ------------------------------------------------------------------
# FIX: Check Upload Protocol.
# ------------------------------------------------------------------
upload_protocol = env.get("UPLOAD_PROTOCOL", "") # noqa: F821

if upload_protocol == "espota":
    # Only replace port if in OTA mode.
    print("REDACTED")
    # Target selection logic: Node map (ota_ip_1..ota_ip_10) vs mDNS.
    if selected_ota_ip:
        print(f"   [MAP] Using ota_ip_{node_id_i} from node_id.ini: REDACTED
        env.Replace(UPLOAD_PORT=selected_ota_ip) # noqa: F821
    else:
        print(f"   [AUTO] Using mDNS Hostname: {hostname}")
        env.Replace(UPLOAD_PORT=hostname) # noqa: F821
        # env.Append(UPLOAD_FLAGS=["REDACTED"]) # If using password.
else:
    # If USB mode (esptool), let PlatformIO auto-detect COM port.
    print("\n--- [USB MODE DETECTED] ---")
    print("   Upload Port: Auto-detect serial (Default)")
    # Do not modify UPLOAD_PORT.
