import os
import configparser
from SCons.Script import Import

Import("env") # noqa: F821

# 1. READ CONFIG FROM EXTERNAL FILE.
config = configparser.ConfigParser()
config.read("node_id.ini")

try:
    gh_id = config.get("settings", "gh_id")
    node_id = config.get("settings", "node_id")
    ota_ip = REDACTED
    gateway_ip = config.get("settings", "gateway_ip", fallback="").strip()
    firmware_version = config.get("settings", "firmware_version", fallback="0.0.0")
    factory_wifi_pass = REDACTED
    factory_api_token = REDACTED
except (configparser.Error, KeyError, OSError):
    print("!!! ERROR: File node_id.ini tidak ditemukan atau format salah !!!")
    gh_id = "0"
    node_id = "0"
    ota_ip = REDACTED
    gateway_ip = ""
    firmware_version = "0.0.0"
    factory_wifi_pass = REDACTED
    factory_api_token = REDACTED

hostname = f"gh-{gh_id}-node-{node_id}.local"

# 3. GENERATE C++ HEADER FILE (Execute to inform firmware of ID).
header_content = f"""#ifndef DYNAMIC_NODE_CONFIG_H
#define DYNAMIC_NODE_CONFIG_H
// Automatically generated by inject_config.py.
// Edit 'node_id.ini' to change values.
#define GH_ID {gh_id}
#define NODE_ID {node_id}
#define FIRMWARE_VERSION "{firmware_version}"
#define FACTORY_WIFI_PASS "REDACTED"
#define FACTORY_API_TOKEN "REDACTED"
#define DEFAULT_GATEWAY_IP "{gateway_ip}"
#endif
"""

output_file = os.path.join("include", "node_config.h")
needs_update = True

if os.path.exists(output_file):
    with open(output_file, "r", encoding="utf-8") as f:
        if f.read().strip() == header_content.strip():
            needs_update = False

if needs_update:
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(header_content)
    print(f"   -> Config header updated: GH={gh_id}, Node={node_id}")
else:
    print(f"   -> Config header unchanged: GH={gh_id}, Node={node_id}")

# ------------------------------------------------------------------
# FIX: Check Upload Protocol.
# ------------------------------------------------------------------
upload_protocol = env.get("UPLOAD_PROTOCOL", "") # noqa: F821

if upload_protocol == "espota":
    # Only replace port if in OTA mode.
    print("REDACTED")
    # Target selection logic: Manual IP vs mDNS.
    if ota_ip:
        print(f"   [OVERRIDE] Using Manual IP from node_id.ini: {ota_ip}")
        env.Replace(UPLOAD_PORT=ota_ip) # noqa: F821
    else:
        print(f"   [AUTO] Using mDNS Hostname: {hostname}")
        env.Replace(UPLOAD_PORT=hostname) # noqa: F821
        # env.Append(UPLOAD_FLAGS=["REDACTED"]) # If using password.
else:
    # If USB mode (esptool), let PlatformIO auto-detect COM port.
    print("\n--- [USB MODE DETECTED] ---")
    print("   Upload Port: Auto-detect serial (Default)")
    # Do not modify UPLOAD_PORT.
