#ifndef DYNAMIC_NODE_CONFIG_H
#define DYNAMIC_NODE_CONFIG_H
// Automatically generated by inject_config.py.
// Edit 'node_id.ini' to change values.
#define GH_ID 2
#define NODE_ID 7
#define FIRMWARE_VERSION "9.9.8"
#define FACTORY_WIFI_PASS "REDACTED"
#define FACTORY_API_TOKEN "REDACTED"
#define DEFAULT_GATEWAY_IP ""
#endif
